export type EffectiveMatchweekMatch = { id: string; originalMatchweek: number; scheduledMatchweek: number | null };
export function effectiveMatchweek(match: Pick<EffectiveMatchweekMatch, "originalMatchweek" | "scheduledMatchweek">) { return match.scheduledMatchweek ?? match.originalMatchweek; }
export function groupByEffectiveMatchweek<T extends EffectiveMatchweekMatch>(matches: T[]) { return matches.reduce((groups, match) => { const week = effectiveMatchweek(match); (groups.get(week) ?? groups.set(week, []).get(week)!).push(match); return groups; }, new Map<number, T[]>()); }
export function isRescheduledMatch(match: EffectiveMatchweekMatch) { return match.scheduledMatchweek !== null && match.scheduledMatchweek !== match.originalMatchweek; }
export function movedMatchweekCounts(matches: EffectiveMatchweekMatch[], week: number) { return { movedIn: matches.filter((match) => isRescheduledMatch(match) && effectiveMatchweek(match) === week).length, movedOut: matches.filter((match) => isRescheduledMatch(match) && match.originalMatchweek === week).length }; }
export function isSupplementalMatchweek(week: number, structuralMaximum: number) { return week > structuralMaximum; }
export function canRescheduleMatch(status: string, competitionStatus: string) { return competitionStatus !== "completed" && !["finished", "completed"].includes(status); }
export function validateRescheduleDraft(currentWeek: number, targetWeek: number, reason: string) { if (!Number.isInteger(targetWeek) || targetWeek < 1 || targetWeek > 99) return "Matchweek ปลายทางต้องเป็นจำนวนเต็มระหว่าง 1 ถึง 99"; if (targetWeek === currentWeek) return "กรุณาเลือก Matchweek ปลายทางที่ต่างจาก Matchweek ปัจจุบัน"; if (!reason.trim()) return "กรุณาระบุเหตุผลการเลื่อนการแข่งขัน"; return ""; }
export function sortRescheduleHistory<T extends { changedAt: string }>(history: T[]) { return [...history].sort((left, right) => right.changedAt.localeCompare(left.changedAt)); }
