/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { AnalyticsSponsorLink } from "@/components/analytics-sponsor-link";
import { homeText, type HomeRow } from "@/lib/home-competition-data";

export function HomeAboutAndMoments() {
  const moments = [["/images/ksw-highlights/highlight-action.jpg", "Matchday Intensity"], ["/images/ksw-highlights/highlight-matchday.jpg", "Sideline Energy"], ["/images/ksw-highlights/highlight-team-huddle.jpg", "Team Spirit"]];
  return <><section className="bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-14 sm:px-6 lg:grid-cols-[.7fr_1.3fr] lg:px-10"><p className="text-xs font-black uppercase tracking-[.2em] text-[#8a641c]">About KSW</p><div><h2 className="text-3xl font-black text-[#061426]">ฟุตบอลที่เชื่อมชุมชนนักกฎหมาย</h2><p className="mt-4 max-w-3xl leading-8 text-slate-600">KSW L.C. สร้างพื้นที่ของการแข่งขัน มิตรภาพ และเครือข่ายวิชาชีพ ผ่านทุกจังหวะในและนอกสนาม</p><Link className="mt-6 inline-flex text-sm font-black text-[#8a641c]" href="/team">รู้จัก KSW มากขึ้น</Link></div></div></section><section className="bg-[#f7f5ef]"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-10"><p className="text-xs font-black uppercase tracking-[.2em] text-[#8a641c]">Latest Moments</p><h2 className="mt-2 text-3xl font-black text-[#061426]">เรื่องราวล่าสุดจาก KSW</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{moments.map(([image, title]) => <article className="relative min-h-56 overflow-hidden bg-[#061426]" key={title}><img alt={title} className="absolute inset-0 size-full object-cover" src={image} /><div className="absolute inset-0 bg-gradient-to-t from-[#061426]/90 to-transparent" /><h3 className="absolute inset-x-0 bottom-0 p-5 text-xl font-black text-white">{title}</h3></article>)}</div><Link className="mt-6 inline-flex text-sm font-black text-[#8a641c]" href="/gallery">ดูแกลเลอรี</Link></div></section></>;
}

export function HomeSponsors({ sponsors }: { sponsors: HomeRow[] }) {
  const activeSponsors = sponsors.filter((sponsor) => sponsor.is_active !== false).sort((a, b) => Number(a.sort_order ?? 0) - Number(b.sort_order ?? 0));
  const groups = [
    ["Main Partner", activeSponsors.filter((sponsor) => homeText(sponsor, ["tier"], "").toLowerCase() === "main")],
    ["Official Partner", activeSponsors.filter((sponsor) => ["official", "partner", "matchday"].includes(homeText(sponsor, ["tier"], "").toLowerCase()))],
    ["Supporter", activeSponsors.filter((sponsor) => !["main", "official", "partner", "matchday"].includes(homeText(sponsor, ["tier"], "").toLowerCase()))],
  ] as const;
  return <section className="bg-[#061426]"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-10"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#f4d58a]">KSW Partnership</p><h2 className="mt-3 text-3xl font-black text-white">Partners & Supporters</h2><p className="mt-4 text-sm leading-7 text-slate-300">ร่วมสนับสนุนชุมชนฟุตบอลนักกฎหมาย และกิจกรรมของ KSW ตลอดฤดูกาล</p><Link className="mt-6 inline-flex text-sm font-black text-[#f4d58a]" href="/partners">Become a KSW Partner</Link></div><div className="space-y-6 border-t border-white/15 pt-6">{groups.map(([label, group]) => group.length ? <div key={label}><p className="mb-3 text-center text-[10px] font-black uppercase tracking-[.2em] text-slate-400">{label}</p><div className="grid grid-cols-2 gap-4 sm:grid-cols-3">{group.map((sponsor) => { const name = homeText(sponsor, ["name"], "Partner"); const logo = homeText(sponsor, ["logo_url"], ""); const link = homeText(sponsor, ["website_url"], ""); const mark = logo ? <img alt={`${name} logo`} className="max-h-16 max-w-full object-contain" src={logo} /> : <span className="text-sm font-black text-slate-400">{name}</span>; return link ? <AnalyticsSponsorLink className="flex min-h-20 items-center justify-center" href={link} key={homeText(sponsor, ["id"], name)} sponsorId={homeText(sponsor, ["id"], "")} target="_blank">{mark}</AnalyticsSponsorLink> : <div className="flex min-h-20 items-center justify-center" key={homeText(sponsor, ["id"], name)}>{mark}</div>; })}</div></div> : null)}</div></div></div></section>;
}
